[minio]
type = s3
provider = Other
access_key_id = proteck
secret_access_key = Gui0004Ma12
region = ch
endpoint = http://192.168.1.10:9000
location_constraint = ch
acl = private

[drive]
type = drive
scope = drive
token = {"access_token":"ya29.a0AUMWg_IekZ7Bb7FJC_qNAzseSHzwRWPLEYUjCJVXzhtxZvBSX2sEI0rVyvl9pdHj-mgsgw-GNqDNaS0NhVTGKQJoLDJOA6S8mCydzxny3GxqHa7tgsdNXepvFIBwxEjq92Yhe5Dnd7oDoH9qB0fbkRogZZrkFQJc2ybSBwASAYdbxt_Zy_f7YkvkauiUTb3bKdsH3kcENAaCgYKAaQSARISFQHGX2MieVFmzazbBg_CCLQoQ-ak7w0209","token_type":"Bearer","refresh_token":"1//0918vG6BF1cnlCgYIARAAGAkSNwF-L9IrwfpX1sgNjDhRuykpJEcviZonRsFDL93HaJe6hqwPinbo0cvtuTHKwc3T0kmjc74mGQc","expiry":"2026-01-14T23:57:00.050991544+01:00"}
team_drive = 

[smb_syno]
type = smb
host = 192.168.1.10
user = proteck
pass = TTkw-UmOn4WFvtRJc_D00V3YTM9aHqLyGkkf

[proteck.ch]
type = sftp
host = proteck.ch
user = proteck
port = 2121
pass = omcdeLjoGSCzS-iD7lzoREmjt1C-BRQNaUpE
shell_type = unix
md5sum_command = none
sha1sum_command = none

[tirarc-corcelles.ch]
type = sftp
host = tirarc-corcelles.ch
user = tirarc-corcelles
port = 2121
pass = 9P1SKTFl-dbdtI0j63T-JqA1pyIWxlgHZ3zt
shell_type = unix
md5sum_command = none
sha1sum_command = none

[minio-surface]
type = s3
provider = Minio
access_key_id = cKa7cXOSfQIyOD5vKgup
secret_access_key = sRc99zI1zHY9qlFQzBAwcLRxtdiVjqKtj4ZEPXYV
region = ch
endpoint = http://192.168.1.11:9000

